### ISSUE TITLE
Future of mpociot/vat-calculator and this Package

### ISSUE THREAD

**Issue by MannikJ** [spaze/vat-calculator#27]
Hi! 

we've been using the [original vat-calculator](https://github.com/mpociot/vat-calculator) for a while now, but we are not very happy about the current state of maintenance. 
Especially at the moment there are a lot of special rules that should be taken care of.

So we found this fork which is also cross-linked from a few issues of the original package and noticed that here has been quite a lot progress recently and the most important issues have been addressed.

So I would like to open the discussion in how far this package could be able to replace the original vat-calculator. And in this context I'd like to ask the practical question about the main differences and if it would be safe to use it as an drop-in-replacement.

I would also like to hear what @mpociot thinks about the future of his package.

**Comment by mpociot** [comment]
Just today I added Dries Vints as a maintainer on this repository as he wanted to help me out here. He also has plans for the future of this package, so maybe he can chime in soon. 
I can't tag him as he hasn't accepted the invitation yet 🙂

**Comment by spaze** [comment]
Hi @MannikJ!

I use this package as a replacement for the original package which I was using before. Just like you, I wasn't very happy with the maintenance the package received and needed some of the existing issues resolved and that was my primary motivation for creating a fork.

And then some other issues appeared, like the temporary rate cuts, which I was able to fix in my fork because suddenly they started to be my issues too. You find some of the issues cross-linked for this exact reason as I still treat the original as "upstream" and for my own reference link the original issues too.

As for the main differences, I try to document the in the [releases page](https://github.com/spaze/vat-calculator/releases) and they are:
- Laravel support removed, can only be used as a standalone lib
- no "get IP" methods
- PHP 7.3 required
- getTaxRateForCountry() removed
- forwardSoapFaults config option removed, always throw exceptions
- PHP 8 support
- Date-based rates

And some more, mostly internal. Whether it can be used as a drop-in replacement depends on whether you use some of the removed features, like Laravel support. I try to preserve the API as much as possible.

Happy that @mpociot has found a co-maintainer and happy to contribute back and file PRs (as I already do), which is my preferred way of doing things. Even happy to contribute everything back as a starting point for a next version maybe, though I'm not sure whether the changes are not just too big (like the Laravel support removal) already.

Hope that clears it up for you.

**Comment by MannikJ** [comment]
First of all thank you both for your quick responses! 

Since the goods news on monday I have kept my feet still waiting for some good news. However, there has still been no update until today and I can't wait a lot longer before I have to decide which way to go. 

So may I ask again, what is the current state? Can we expect any updates on [mpociot/vat-calculator](https://github.com/mpociot/vat-calculator) or will it be the best not to rely on that and migrate to this @spaze's fork? 

Would be nice if @driesvints could also put his two cents in...

**Comment by driesvints** [comment]
Hey all, I've recently gotten access to this repository from @mpociot and plan on putting in some work soon. Probably by solving some of the bugs in the current stable release and work towards a proper new major version. I can't say when exactly that would be but hoping to dig into it sooner rather than later.

**Comment by MannikJ** [comment]
Welcome :) 
That sounds very promising. I would actually really appreciate not having to migrate to another package.
Do you already have a priority list? Speaking for us [this one](https://github.com/mpociot/vat-calculator/pull/102) is the most important. If you could prepare a release including this PR we would be a huge step further and I would be much more relaxed.

**Comment by driesvints** [comment]
Not yet but fixing all of the calculations to the proper percentages definitely will be on top of my list.

**Comment by driesvints** [comment]
If need be, use a fork for now. Hoping to address those specific issues soon.

**Comment by Fossil01** [comment]
I switched to this fork and was happy that not a lot of additional work was needed to make it work. Basically just writing some own code to get the country from the IP. Cheers @spaze

**Comment by spaze** [comment]
Relevant notes from @driesvints:

> Hi, I regret to inform you that for now, I'm not going to pursue new features to this library [[driesvints/vat-calculator](https://github.com/driesvints/vat-calculator)]. I might pick this up in the future again but for now, it's best that you fork this library if you need this. Thanks

-- https://github.com/driesvints/vat-calculator/pull/114#issuecomment-981096046

> Chances are very slim that I'll find time soon to look into this. There's also the thing that with Stripe Tax now this package has become much less relevant. As for my personal priorities I won't be looking into much new features for this package soon but will be updating it for future PHP versions etc. I simply don't have the bandwidth atm to give these PR's the time they deserve.

-- https://github.com/driesvints/vat-calculator/pull/95#issuecomment-952969619

To be as clear as possible, we're using this lib at https://report-uri.com/ and even though we also use Stripe, we're not planning to stop using or deprecate this lib.

**Comment by driesvints** [comment]
@spaze would you maybe be interested in co-maintaining the original vat-calculator package?
